- platform: template
  sensors:
    person3_travel:
      friendly_name: "person3's location"
      entity_id: input_boolean.person3_home, device_tracker.person3_mobile, sensor.person3s_time_to_home_2, input_select.person3_status_dropdown
      value_template: >-
        {% if is_state("input_boolean.person3_home", "on") %}
          {{ states("input_select.person3_status_dropdown") }}
        {% elif is_state("device_tracker.person3_mobile", "home") and is_state("input_boolean.person3_home", "off") %}
          Near home ({{ states("input_select.person3_status_dropdown") }})
        {% elif not is_state("device_tracker.person3_mobile", "not_home") %}
          At {{ states("device_tracker.person3_mobile") }}
        {% else %}
          {{ state_attr('sensor.person3s_time_to_home_2', 'duration') }} to home
        {% endif %}
