- platform: template
  sensors:
    person4_travel:
      friendly_name: "person4's location"
      entity_id: input_boolean.person4_home, device_tracker.person4_mobile, sensor.person4s_time_to_home, input_select.person4_status_dropdown
      value_template: >-
        {% if is_state("input_boolean.person4_home", "on") %} 
          {{ states("input_select.person4_status_dropdown") }}
        {% elif is_state("device_tracker.person4_mobile", "home") and is_state("input_boolean.person4_home", "off") %}
          Near home ({{ states("input_select.person4_stats_dropdown") }})
        {% elif not is_state("device_tracker.person4_mobile", "not_home") %}
          At {{ states("device_tracker.person4_mobile") }}
        {% else %}
          {{ state_attr('sensor.person4s_time_to_home', 'duration')|round(0) }} {{ state_attr('sensor.person4s_time_to_home', 'unit_of_measurement') }} to home
        {% endif %}
