initial_state: 'on'
alias: 'Bedtime'
trigger:
  - platform: state
    entity_id: input_boolean.person3_is_awake
    to: 'off'
  - platform: state
    entity_id: input_boolean.person2_is_awake
    to: 'off'
  - platform: state
    entity_id: input_boolean.person1_is_awake
    to: 'off'
condition:
  - condition: and
    conditions:
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.person3_home
        state: 'off'
      - condition: and
        conditions:
        - condition: state
          entity_id: input_boolean.person3_is_awake
          state: 'off'
        - condition: state
          entity_id: input_boolean.person3_home
          state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.person2_home
        state: 'off'
      - condition: state
        entity_id: input_boolean.person2_travelling
        state: 'on'
      - condition: and
        conditions:
        - condition: state
          entity_id: input_boolean.person2_is_awake
          state: 'off'
        - condition: state
          entity_id: input_boolean.person2_home
          state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.person1_home
        state: 'off'
      - condition: and
        conditions:
        - condition: state
          entity_id: input_boolean.person1_is_awake
          state: 'off'
        - condition: state
          entity_id: input_boolean.person1_home
          state: 'on'
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.bedtime
